fix <revision>/<version> checking
git-svn-id: svn+ssh://svn.cern.ch/reps/CMSDMWM/Infrastructure/trunk@12204 4525493e-7705-40b1-a816-d608a930855b

diff --git a/BuilderAgent/build-funcs b/BuilderAgent/build-funcs
--- a/BuilderAgent/build-funcs
+++ b/BuilderAgent/build-funcs
@@ -49,21 +49,19 @@ job_process_file() {
     exit 0 # job succeeded
 }
 
-# Returns 0 if needs rebuild; 1 otherwise
+# Returns 0 delta processing succeeds; 1 otherwise
 process_delta() {
     local CMSDIST=$1; shift;
-    local REBUILD=1
 
-    # Enables brace expansion (disabled by default when running scripts)
-    set -B 
+    set -B # Enables brace expansion (disabled by default when running scripts) 
 
     # This loop process each delta
     while [ "$1" = "+" ]; do
+        # Gets REV and VER specified on delta
 	local REV=${2%%\/*}; local VER=${2#*\/}; shift 2
-	[ "$VER" = "$REV" ] && VER="*"
-	
+	[ "$VER" = "$REV" ] && VER="*"  # Blank VER means "*"
 	[ "$REV" = "HEAD" -a "$VER" = "*" ] &&
-	    { echo "Malformed delta - you must specify version when using HEAD"; exit 1; }
+	    { echo "Malformed delta - you must specify version when using HEAD"; return 1; }
 
 	# This loop process files affected by the delta
 	while [ "$1" != "+" -a -n "$1" ]; do
@@ -71,38 +69,35 @@ process_delta() {
 	    # The 'eval echo' below is needed because brace expansion gets
 	    # done before variable expansion.
 	    for F in $(eval echo $BUILDER_ROOT/var/CMSDIST.HEAD/$1); do
-		local FNAME=${F##*/} # takes only the file name
-		echo "DEBUG: file is <$F>"
-		[ -f "$F" ] ||
-	            { echo "File pattern $FNAME could not be found in $BUILDER_ROOT/var/CMSDIST.HEAD/"; exit 1; }
-		if [ ! -f "$CMSDIST/$FNAME" ]; then 
-		    cvs co -r $REV -d $CMSDIST CMSDIST/$FNAME ||
-			{ echo "Error while getting CMSDIST/$FNAME from CVS"; exit 1; }
-		    REBUILD=0
-		fi
-		
-		local CURRVER=$(head -n1 $CMSDIST/$FNAME| tr -s " " | cut -d" " -f5 2>/dev/null)
-		if [ "$VER" != "*" -a "$CURRVER" != "$VER" ]; then
-		    cvs up -r $REV $CMSDIST/$FNAME ||
-			{ echo "Error while getting CMSDIST/$FNAME from CVS"; exit 1; }
-		    CURRVER=$(head -n1 $CMSDIST/$FNAME| tr -s " " | cut -d" " -f5 2>/dev/null)
-		    [ "$CURRVER" = "$VER" ] ||
-			{ echo "Could not get version $VER from $REV for $FNAME"; exit 1; }
-		    REBUILD=0
-		fi
+		test -f "$F" || 
+                    { echo "Pattern $1 doesnt expand to any existent file"; return 1; }
 
-		local STAG=$(cvs status $CMSDIST/$FNAME |grep "Sticky Tag"| tr "\t" " " | cut -d" " -f7)
-		if [ "$VER" = "*" -a "$STAG" != "$REV" ]; then
-		    # revision will never be HEAD here
-		    cvs up -r $REV $CMSDIST/$FNAME ||
-			{ echo "Error while getting CMSDIST/$FNAME from CVS"; exit 1; }
-		    REBUILD=0
-		fi
+		local FNAME=${F##*/} # takes the file name without full path
+		echo "DEBUG: file is <$F>"
+
+		# Checks out the file if it doesnt yet exist
+		[ -f "$CMSDIST/$FNAME" ] ||
+		    { cvs co -r $REV -d $CMSDIST CMSDIST/$FNAME || return 1; }
+
+		local FVER=$(head -n1 $CMSDIST/$FNAME| tr -s " " | cut -d" " -f5 2>/dev/null)
+		local FREV=$(grep "/$FNAME/" $CMSDIST/CVS/Entries | cut -d/ -f6 | cut -b2-)
+                [ -z "$FREV" ] && FREV=$(grep "/$FNAME/" $CMSDIST/CVS/Entries | cut -d/ -f3)
+
+                [ "$REV" = "HEAD" -a "$VER" != "$FVER" ] &&
+                   { cvs up -A $CMSDIST/$FNAME || return 1; }
+                [ "$REV" != "HEAD" -a "$REV" != "$FREV" ] &&
+                   { cvs up -r $REV $CMSDIST/$FNAME || return 1; } # Make sure the revision match
+                [ "$REV" != "HEAD" -a "$REV" = "$FREV" -a "$VER" != "*" -a "$VER" != "$FVER" ] &&
+                   { cvs up -r $REV $CMSDIST/$FNAME || return 1; } # Refetch REV to try to match VER
+
+		FVER=$(head -n1 $CMSDIST/$FNAME| tr -s " " | cut -d" " -f5 2>/dev/null)
+                [ "$VER" != "*" -a "$VER" != "$FVER" ] &&
+  		   { echo "Could not match $VER for file $FNAME"; return 1; }
 	    done
 	    shift
 	done
     done
-    return $REBUILD
+    return 0
 }
 
 job_build() {
