Support multi-architectures.
From: Diego da Silva Gomes <diego@cern.ch>


git-svn-id: svn+ssh://svn.cern.ch/reps/CMSDMWM/Infrastructure/trunk@14128 4525493e-7705-40b1-a816-d608a930855b

diff --git a/BuilderAgent/build-funcs b/BuilderAgent/build-funcs
--- a/BuilderAgent/build-funcs
+++ b/BuilderAgent/build-funcs
@@ -22,9 +22,9 @@ run_job() {
 
 NAME='[.a-zA-Z0-9_\-]+'
 GLOB='([\*\{\}\?\^\!\.\,a-zA-Z0-9_\-]|\]?|\[?)+'
-BTAG='HG[0-9]{4}[a-zA-Z0-9]+'
+BTAG='HG[0-9]{4}[-a-zA-Z0-9]+'
 DELTA="[ \#]+\+ ?$NAME(\/$NAME|\/\*)?( $GLOB)+"
-NEWENTRY="(^|\#)$BTAG $NAME($DELTA)* *($|\#)"
+ENTRY="$BTAG $NAME( \@($ARCHS_RE))($DELTA)* *($|\#)"
 
 job_process_file() {
     init_job
@@ -41,7 +41,7 @@ job_process_file() {
     while read -d "#" ENTRY; do
 	echo " * Found entry <$ENTRY>"
 	run_job job_build $REPO $ENTRY
-    done <<< $(grep -v "#" CMSDIST.HEAD/$FILE | tr -s " \n" " #" | egrep -o "$NEWENTRY" | tr "#\n" " #")
+    done <<< $(grep -v "#" CMSDIST.HEAD/$FILE | tr -s " \n" " #" | egrep -o "$ENTRY" | tr "#\n" " #")
 
     wait;
     cat $LOG_FILE.*.$REPO.chk 2>/dev/null; echo;
@@ -103,21 +103,21 @@ process_delta() {
 
 job_build() {
     init_job
-    local REPO=$1; shift;
+    local REPO=$1; local BASETAG=$2; local PROJ=$3; local ARCH=${4:1}; shift 4;
     local CMSDIST="CMSDIST.$REPO"
-    local BASETAG=$1; local PROJ=$2; shift 2;
     local CMSBUILD=$CMSBUILD17
     case $BASETAG in
-      HG12* | HG111* | HG110[789]* ) CMSBUILD=$CMSBUILD18 ;;
+      HG12* | HG111* ) CMSBUILD=$CMSBUILD19 ;;
+      HG110[789]* )    CMSBUILD=$CMSBUILD18 ;;
     esac
 
-    exec &> $LOG_FILE.$PROJ.$REPO.chk  # Set new log file
+    exec &> $LOG_FILE.$PROJ.$ARCH.$REPO.chk  # Set new log file
 
-    echo; echo "---------[$BASETAG $PROJ $CMSBUILD]----------"
-    mkdir -p $BUILDS/$PROJ; cd $BUILDS/$PROJ
-    acquire_lock $PROJ ||
-	{ echo "Project $PROJ locked by other process. Skipping."; exit 1; }
-    trap 'def_job_exit_trap; release_lock $PROJ' EXIT
+    echo; echo "---------[$BASETAG $PROJ@$ARCH $CMSBUILD]----------"
+    mkdir -p $BUILDS/${PROJ}_${ARCH}; cd $BUILDS/${PROJ}_${ARCH}
+    acquire_lock ${PROJ}_${ARCH} ||
+	{ echo "Project ${PROJ}_${ARCH} locked by other process. Skipping."; exit 1; }
+    trap 'def_job_exit_trap; release_lock ${PROJ}_${ARCH}' EXIT
 
 
     local DIRSUM=$(cat $CMSDIST/* 2>/dev/null | md5sum | tr -d ' -')
@@ -135,27 +135,27 @@ job_build() {
     [ "$DIRSUM" = "$(cat $CMSDIST/* 2>/dev/null | md5sum | tr -d ' -')" ] &&
         { echo "Nothing changed. Build not necessary"; exit 1; }
 
-    echo "Rebuilding project $PROJ. See logfile $LOG_FILE.$PROJ.$REPO"
+    echo "Rebuilding project $PROJ@$ARCH. See logfile $LOG_FILE.$PROJ.$ARCH.$REPO"
 
-    exec &> $LOG_FILE.$PROJ.$REPO  # Set new log file
+    exec &> $LOG_FILE.$PROJ.$ARCH.$REPO  # Set new log file
 
     # Builds it
     [ -d "tmp" -o -d "w" ] && rm -rf tmp w
-    run_job $CMSBUILD -a $SCRAM_ARCH -c $CMSDIST -j 5 --builders=10 \
+    run_job $CMSBUILD -a $ARCH -c $CMSDIST -j 5 --builders=10 \
                       --repository=$REPO build $PROJ --work-dir=w
-    wait % || { echo "BUILD: project $PROJ failed to build."; exit 2; }
+    wait % || { echo "BUILD: project $PROJ@$ARCH failed to build."; exit 2; }
 
     # Rpm list generated by this build
-    local RPM_FILES=$(find $BUILDS/$PROJ/w/RPMS/$SCRAM_ARCH/ -name "*rpm" | tr '\n' ' ')
+    local RPM_FILES=$(find $BUILDS/${PROJ}_${ARCH}/w/RPMS/$ARCH/ -name "*rpm" | tr '\n' ' ')
     [ -z "$RPM_FILES" ] &&
-    	{ echo "BUILD: project $PROJ produced no new RPMs. Skipping."; exit 2; }
+        { echo "BUILD: project $PROJ@$ARCH produced no new RPMs. Skipping."; exit 2; }
 
     # Now uploads the RPMs
-    run_job job_upload $REPO $PROJ $CMSBUILD
-    wait % || { echo "BUILD: failed to upload $PROJ to repo $REPO"; exit 2; }
+    run_job job_upload $REPO $PROJ $CMSBUILD $ARCH
+    wait % || { echo "BUILD: failed to upload $PROJ@$ARCH to repo $REPO"; exit 2; }
 
     # Publishes the new RPMs and tags CMSDIST
-    update_status $REPO $PROJ $RPM_FILES
+    update_status $REPO $PROJ $ARCH $RPM_FILES
 
     exit 0
 }
@@ -167,30 +167,30 @@ job_build() {
 job_upload() {
     init_job
     trap '' EXIT # there is nothing to clean here
-    trap 'echo "UPLOAD: cannot TERM while uploading $PROJ"' SIGINT SIGTERM
-    local REPO=$1; local PROJ=$2; local CMSBUILD=$3
+    trap 'echo "UPLOAD: cannot TERM while uploading $PROJ@$ARCH"' SIGINT SIGTERM
+    local REPO=$1; local PROJ=$2; local CMSBUILD=$3; local ARCH=$4
 
-    cd $BUILDS/$PROJ
+    cd $BUILDS/${PROJ}_${ARCH}
 
-    $CMSBUILD --sync-back -a $SCRAM_ARCH -c CMSDIST.$REPO -j 5 --builders=10 \
+    $CMSBUILD --sync-back -a $ARCH -c CMSDIST.$REPO -j 5 --builders=10 \
               --repository=$REPO upload $PROJ --work-dir=w ||
-       { echo "UPLOAD: project $PROJ failed to upload.";  exit 1; }
+       { echo "UPLOAD: project $PROJ@$ARCH failed to upload.";  exit 1; }
 
     exit 0 # upload succeeded
 }
 
 update_status() {
-    local REPO=$1; local PROJ=$2; shift 2;
+    local REPO=$1; local PROJ=$2; local ARCH=$3; shift 3
 
     local RPMS=""
     for RPM; do
-	RPM=${RPM%-1-1.$SCRAM_ARCH.rpm} # strip stuff from the end
+	RPM=${RPM%-1-1.$ARCH.rpm} # strip stuff from the end
 	RPM=${RPM##*/} # strip the dir path from the beginning
 	RPMS+=" $RPM"
     done
 
     # Creates a new tag
-    local TAG="builder_$(date +%Y-%m-%d_%H-%M-%S)_${PROJ}"
+    local TAG="bld_$(date +%s)_${PROJ}_${ARCH}"
     cvs tag -F $TAG CMSDIST.$REPO
 
     # Prepares the status information
@@ -201,8 +201,8 @@ update_status() {
     for RPM in $RPMS; do
 	local PKG=$(echo $RPM|cut -d"+" -f2)
 	local ENTRY="| $PKG  | $RPM  | $DATE  | $DIFF  | $TAG  |"
-	echo "$ENTRY" >> $WEB/$PKG.$REPO.history
-	echo -n "$ENTRY" > $WEB/$PKG.$REPO
+	echo "$ENTRY" >> $WEB/$PKG.$ARCH.$REPO.history
+	echo -n "$ENTRY" > $WEB/$PKG.$ARCH.$REPO
     done
 
     return 0
